// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type AvailabilitySlot struct {
	Start string `json:"start"`
	End   string `json:"end"`
}

type AvailabilitySlotInput struct {
	Start string `json:"start"`
	End   string `json:"end"`
}

type Booking struct {
	ID           string   `json:"id"`
	FacilityID   *string  `json:"facilityId,omitempty"`
	UserID       *string  `json:"userId,omitempty"`
	Status       *string  `json:"status,omitempty"`
	StartsAt     *string  `json:"startsAt,omitempty"`
	EndsAt       *string  `json:"endsAt,omitempty"`
	Participants *int     `json:"participants,omitempty"`
	Price        *float64 `json:"price,omitempty"`
	Notes        *string  `json:"notes,omitempty"`
	CreatedAt    *string  `json:"createdAt,omitempty"`
	UpdatedAt    *string  `json:"updatedAt,omitempty"`
}

type BookingInput struct {
	FacilityID   string   `json:"facilityId"`
	UserID       string   `json:"userId"`
	StartsAt     string   `json:"startsAt"`
	EndsAt       string   `json:"endsAt"`
	Participants *int     `json:"participants,omitempty"`
	Price        *float64 `json:"price,omitempty"`
	Notes        *string  `json:"notes,omitempty"`
}

type BookingPatchInput struct {
	StartsAt *string `json:"startsAt,omitempty"`
	EndsAt   *string `json:"endsAt,omitempty"`
	Notes    *string `json:"notes,omitempty"`
}

type Facility struct {
	ID          string         `json:"id"`
	Name        *string        `json:"name,omitempty"`
	City        *string        `json:"city,omitempty"`
	Address     *string        `json:"address,omitempty"`
	Type        *string        `json:"type,omitempty"`
	Amenities   []string       `json:"amenities,omitempty"`
	Description *string        `json:"description,omitempty"`
	Maintenance []*Maintenance `json:"maintenance,omitempty"`
	CreatedAt   *string        `json:"createdAt,omitempty"`
	UpdatedAt   *string        `json:"updatedAt,omitempty"`
}

type FacilityInput struct {
	Name        string              `json:"name"`
	City        string              `json:"city"`
	Address     string              `json:"address"`
	Type        string              `json:"type"`
	Amenities   []string            `json:"amenities,omitempty"`
	Description *string             `json:"description,omitempty"`
	Maintenance []*MaintenanceInput `json:"maintenance,omitempty"`
}

type FacilityPatchInput struct {
	Name        *string  `json:"name,omitempty"`
	City        *string  `json:"city,omitempty"`
	Address     *string  `json:"address,omitempty"`
	Type        *string  `json:"type,omitempty"`
	Amenities   []string `json:"amenities,omitempty"`
	Description *string  `json:"description,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Maintenance struct {
	Start string  `json:"start"`
	End   string  `json:"end"`
	Note  *string `json:"note,omitempty"`
}

type MaintenanceInput struct {
	Start string  `json:"start"`
	End   string  `json:"end"`
	Note  *string `json:"note,omitempty"`
}

type Mutation struct {
}

type ProfileUpdateInput struct {
	FullName *string `json:"fullName,omitempty"`
	Phone    *string `json:"phone,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	FullName string  `json:"fullName"`
	Role     *string `json:"role,omitempty"`
	Phone    *string `json:"phone,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Email     *string `json:"email,omitempty"`
	FullName  *string `json:"fullName,omitempty"`
	Role      *string `json:"role,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}
