package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"kursovaya_aksp/services/api-gateway/internal/graphql/generated"
	"kursovaya_aksp/services/api-gateway/internal/graphql/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.User, error) {
	payload := registerRequest{
		Email:    input.Email,
		Password: input.Password,
		FullName: input.FullName,
	}
	if input.Role != nil {
		payload.Role = *input.Role
	}
	if input.Phone != nil {
		payload.Phone = *input.Phone
	}
	var user userDTO
	if err := r.doJSON(ctx, http.MethodPost, r.identityURL+"/auth/register", payload, &user); err != nil {
		return nil, err
	}
	return userMap(user), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	var resp authResponse
	if err := r.doJSON(ctx, http.MethodPost, r.identityURL+"/auth/login", loginRequest{
		Email:    input.Email,
		Password: input.Password,
	}, &resp); err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: resp.Token, User: userMap(resp.User)}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.ProfileUpdateInput) (*model.User, error) {
	if input.FullName == nil && input.Phone == nil {
		return nil, errors.New("profile update requires fullName or phone")
	}
	payload := profileUpdateRequest{}
	if input.FullName != nil {
		payload.FullName = *input.FullName
	}
	if input.Phone != nil {
		payload.Phone = *input.Phone
	}
	var user userDTO
	if err := r.doJSON(ctx, http.MethodPatch, r.identityURL+"/users/me", payload, &user); err != nil {
		return nil, err
	}
	return userMap(user), nil
}

// CreateFacility is the resolver for the createFacility field.
func (r *mutationResolver) CreateFacility(ctx context.Context, input model.FacilityInput) (*model.Facility, error) {
	maintenance, err := maintenanceFromInput(input.Maintenance)
	if err != nil {
		return nil, err
	}
	payload := facilityCreateRequest{
		Name:        input.Name,
		City:        input.City,
		Address:     input.Address,
		Type:        input.Type,
		Amenities:   append([]string{}, input.Amenities...),
		Maintenance: maintenance,
	}
	if input.Description != nil {
		payload.Description = *input.Description
	}
	var facility facilityDTO
	if err := r.doJSON(ctx, http.MethodPost, r.facilityURL+"/facilities", payload, &facility); err != nil {
		return nil, err
	}
	return facilityMap(facility), nil
}

// UpdateFacility is the resolver for the updateFacility field.
func (r *mutationResolver) UpdateFacility(ctx context.Context, id string, input model.FacilityPatchInput) (*model.Facility, error) {
	if input.Name == nil && input.City == nil && input.Address == nil && input.Type == nil && input.Description == nil && input.Amenities == nil {
		return nil, errors.New("facility update requires at least one field")
	}
	payload := facilityUpdateRequest{
		Name:        input.Name,
		City:        input.City,
		Address:     input.Address,
		Type:        input.Type,
		Description: input.Description,
	}
	if input.Amenities != nil {
		copy := append([]string{}, input.Amenities...)
		payload.Amenities = &copy
	}
	var facility facilityDTO
	endpoint := fmt.Sprintf("%s/facilities/%s", r.facilityURL, id)
	if err := r.doJSON(ctx, http.MethodPatch, endpoint, payload, &facility); err != nil {
		return nil, err
	}
	return facilityMap(facility), nil
}

// DeleteFacility is the resolver for the deleteFacility field.
func (r *mutationResolver) DeleteFacility(ctx context.Context, id string) (bool, error) {
	endpoint := fmt.Sprintf("%s/facilities/%s", r.facilityURL, id)
	if err := r.doJSON(ctx, http.MethodDelete, endpoint, nil, nil); err != nil {
		if errors.Is(err, errNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// UpdateFacilityAvailability is the resolver for the updateFacilityAvailability field.
func (r *mutationResolver) UpdateFacilityAvailability(ctx context.Context, id string, slots []*model.AvailabilitySlotInput) (bool, error) {
	converted, err := availabilityFromInput(slots)
	if err != nil {
		return false, err
	}
	endpoint := fmt.Sprintf("%s/facilities/%s/availability", r.facilityURL, id)
	if err := r.doJSON(ctx, http.MethodPut, endpoint, availabilityUpdateRequest{Slots: converted}, nil); err != nil {
		if errors.Is(err, errNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, input model.BookingInput) (*model.Booking, error) {
	startsAt, err := parseRFC3339(input.StartsAt)
	if err != nil {
		return nil, fmt.Errorf("invalid startsAt: %w", err)
	}
	endsAt, err := parseRFC3339(input.EndsAt)
	if err != nil {
		return nil, fmt.Errorf("invalid endsAt: %w", err)
	}
	payload := bookingCreateRequest{
		FacilityID:   input.FacilityID,
		UserID:       input.UserID,
		StartsAt:     startsAt,
		EndsAt:       endsAt,
		Participants: input.Participants,
		Price:        input.Price,
		Notes:        input.Notes,
	}
	var booking bookingDTO
	if err := r.doJSON(ctx, http.MethodPost, r.bookingURL+"/bookings", payload, &booking); err != nil {
		return nil, err
	}
	return bookingMap(booking), nil
}

// UpdateBooking is the resolver for the updateBooking field.
func (r *mutationResolver) UpdateBooking(ctx context.Context, id string, input model.BookingPatchInput) (*model.Booking, error) {
	if input.StartsAt == nil && input.EndsAt == nil && input.Notes == nil {
		return nil, errors.New("booking update requires at least one field")
	}
	startPtr, err := timePtrFromString(input.StartsAt)
	if err != nil {
		return nil, fmt.Errorf("invalid startsAt: %w", err)
	}
	endPtr, err := timePtrFromString(input.EndsAt)
	if err != nil {
		return nil, fmt.Errorf("invalid endsAt: %w", err)
	}
	payload := bookingPatchRequest{
		StartsAt: startPtr,
		EndsAt:   endPtr,
		Notes:    input.Notes,
	}
	var booking bookingDTO
	endpoint := fmt.Sprintf("%s/bookings/%s", r.bookingURL, id)
	if err := r.doJSON(ctx, http.MethodPatch, endpoint, payload, &booking); err != nil {
		return nil, err
	}
	return bookingMap(booking), nil
}

// CancelBooking is the resolver for the cancelBooking field.
func (r *mutationResolver) CancelBooking(ctx context.Context, id string) (*model.Booking, error) {
	return r.mutateBookingStatus(ctx, id, "cancel")
}

// ConfirmBooking is the resolver for the confirmBooking field.
func (r *mutationResolver) ConfirmBooking(ctx context.Context, id string) (*model.Booking, error) {
	return r.mutateBookingStatus(ctx, id, "confirm")
}

// DeleteBooking is the resolver for the deleteBooking field.
func (r *mutationResolver) DeleteBooking(ctx context.Context, id string) (bool, error) {
	endpoint := fmt.Sprintf("%s/bookings/%s", r.bookingURL, id)
	if err := r.doJSON(ctx, http.MethodDelete, endpoint, nil, nil); err != nil {
		if errors.Is(err, errNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// Facilities is the resolver for the facilities field.
func (r *queryResolver) Facilities(ctx context.Context, city *string, typeArg *string) ([]*model.Facility, error) {
	items, err := r.listFacilities(ctx, stringVal(city), stringVal(typeArg))
	if err != nil {
		return nil, err
	}
	return facilityResult(items), nil
}

// Facility is the resolver for the facility field.
func (r *queryResolver) Facility(ctx context.Context, id string) (*model.Facility, error) {
	item, err := r.getFacility(ctx, id)
	if errors.Is(err, errNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return facilityMap(*item), nil
}

// Bookings is the resolver for the bookings field.
func (r *queryResolver) Bookings(ctx context.Context, facilityID *string, userID *string) ([]*model.Booking, error) {
	items, err := r.listBookings(ctx, stringVal(facilityID), stringVal(userID))
	if err != nil {
		return nil, err
	}
	return bookingResult(items), nil
}

// Availability is the resolver for the availability field.
func (r *queryResolver) Availability(ctx context.Context, facilityID string) ([]*model.AvailabilitySlot, error) {
	slots, err := r.getAvailability(ctx, facilityID)
	if errors.Is(err, errNotFound) {
		return []*model.AvailabilitySlot{}, nil
	}
	if err != nil {
		return nil, err
	}
	return availabilityResult(slots), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func (r *mutationResolver) mutateBookingStatus(ctx context.Context, id, action string) (*model.Booking, error) {
	var booking bookingDTO
	endpoint := fmt.Sprintf("%s/bookings/%s/%s", r.bookingURL, id, action)
	if err := r.doJSON(ctx, http.MethodPost, endpoint, nil, &booking); err != nil {
		return nil, err
	}
	return bookingMap(booking), nil
}
